import 'package:flutter/material.dart';

const List<Map<String, dynamic>> petData = [
  {
    'img': 'https://picsum.photos/250?image=9',
    'title': 'Buddy',
    'subTitle': 'Mongrel',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'age': '1 Year',
    'status': 'Fostered',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'title': 'Charlie',
    'subTitle': 'Alaskan Malamute',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'age': '2 Year',
    'status': 'Adopted',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Beagle',
    'title': 'Cooper',
    'age': '1 Year',
    'status': 'Abandoned',
    'statusColor': Color(0xff991B1B),
    'borderColor': Color(0xffFEE2E2),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'title': 'Miloo',
    'subTitle': 'Gordon Setter',
    'age': '3 Year',
    'status': 'Available for foster',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Mongrel',
    'title': 'Buddy',
    'age': '4 Year',
    'status': 'Adopted',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Pixiebob Cat',
    'title': 'Rocky',
    'age': '1 Year',
    'status': 'Vaccinated',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Maine Coon',
    'title': 'Teddy',
    'age': '2 Year',
    'status': 'Fostered',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Munchkin Cat',
    'title': 'Luna',
    'age': '1 Year',
    'status': 'Adopted',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Siberian Cat',
    'title': 'Zoe',
    'age': '1 Year',
    'status': 'Vaccination Pending',
    'statusColor': Color(0xff92400E),
    'borderColor': Color(0xffFEF3C7),
  },
  {
    'img': 'https://picsum.photos/250?image=9',
    'imgIcon': Icons.swipe_up_alt_outlined,
    'subTitle': 'Mongrel',
    'title': 'Bailey',
    'age': '2 Year',
    'status': 'Adopted',
    'statusColor': Color(0xff065F46),
    'borderColor': Color(0xffD1FAE5),
  },
];
